package projecteulersolutions

/*
Problem 2
~~~~~~~~~~
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting 1 and 2, the first 10
terms will be: 1,2,3,5,8,13,21,34,55,89,...

By considering the terms in the Fibonacci sequence whose
values do not exceed four million, find the sum of the
even-valued terms.
*/

func SumOfFibEvenTerms(c int) (sum int) {
	a, b := 0, 1

	// a less than c, in we case 4 millons
	for a < c {
		if a%2 == 0 {
			sum += a
		}
		a, b = b, a+b
	}

	return
}
